spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8888/
          predicates:
            - Path= /commandes/**
        - id: r2
          uri: http://localhost:9999/
          predicates:
            - Path= /professeurs/**